"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mq.py']
DATA_FILES = []
OPTIONS = {
	'iconfile':'icons/mq.icns',
        'plist': {'CFBundleShortVersionString':'0.1.0',}
}

setup(
    app=APP,
    name='Movie Quantizer',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
